/' include of C4 libaries '/
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

/' Link Color white '/
skinparam {
  HyperlinkColor #ffffff
}

/' Persons '/
/' Predefined Persons to be used in other PlantUMLs '/

!unquoted procedure Teacher($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person_Ext($alias, "Teacher", "A teacher using the adaptive learning system.")
!endprocedure
!unquoted procedure Student($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person_Ext($alias, "Student", "A student using the adaptive learning system.")
!endprocedure
!unquoted procedure Support($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person($alias, "Service & Support", "A internal role supporting our users and customers.")
!endprocedure
!unquoted procedure Content($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person($alias, "Content manager", "A internal role in Marketing writing and concepting content.")
!endprocedure

/' Systems '/
/' Predefined Systems to be used in other PlantUMLs '/

!unquoted procedure ALS($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/937361479/5.1+Adaptive+Learning+System Adaptive Learning System]]", "The main learning system allowing students to learn subjects interactively.")
!endprocedure

!unquoted procedure CCS($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/968753212/5.5+Content+Creation+System Content Creation System]]", "Tools and Applications that allow content authoring and publishing to a content store.")
!endprocedure

!unquoted procedure NIA($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/936771705/5.2+Integration+System Integration System]]", "The System handling authentication and making api adaptiomns that allow for integration with both internal and external identity and group providers.")
!endprocedure

!unquoted procedure DATA($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/940703828/5.4+Learning+Analytics+Systems Learning Analytics System]]", "The Collection of systems and tools providingstandard and self service reporting on interactions in the bettermarks platform.")
!endprocedure

!unquoted procedure CULM($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/969343005/5.3+Customer+User+Lifecycle+Management+System Customer & User Lifecycle Management System]]", "Tools and Applications that helps to manage and interact with users and customers during their lifecycle at bettermarks.")
!endprocedure

!unquoted procedure EIDM($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
System_Ext($alias, "Integration Partner System", "An external entity that provides user identity and/or user/group management services.")
!endprocedure

/' Containers in the Systems of bettermarks '/

/' Container in CULM '/
/' Predefined Container in the CULM Domain to be used in other PlantUMLs '/

!unquoted procedure GLU($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/1469972495/5.3.1+GLU GLU]]", "Container", "Provides IDM and User/Group Management to the User and Service & Support.")
!endprocedure

!unquoted procedure Licensing($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/1470431242/5.3.2+Licensing Licensing]]", "Component", "Provides the client application with licenses related to products and entities within the hierarchy (groups).")
!endprocedure

!unquoted procedure LicensingShop($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container($alias, "[[https://bettermarks.atlassian.net/wiki/spaces/SYSDOCS/pages/1470595073/5.3.3+Licensing+Shop Licensing Shop]]", "Component", "Provides the shop service to purchase licenses with the client application.")
!endprocedure

!unquoted procedure Mapping($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container($alias, "Mapping Service", "Container", "Provides a Service to map internal and external IDs within bettermarks.")
!endprocedure

!unquoted procedure Website($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "Website", "Wordpress | Raidboxes", "Delivers the static content and provides several forms to contact internal roles.")
!endprocedure

!unquoted procedure Email($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "Email Application", "Microsoft 365", "The Microsoft e-mail system.")
!endprocedure

!unquoted procedure Helpdesk($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "Zammad", "Helpdesk SaaS", "Provides a ticket system and a helpdesk for Service&Support.")
!endprocedure

!unquoted procedure CRM($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "1CRM", "CRM SaaS", "Application to manage and cummunicate with customers.")
!endprocedure

!unquoted procedure Brevo($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "Brevo", "Email SaaS", "Email Service for Campaigns, Transactional Emails and CRM functionalities.")
!endprocedure

!unquoted procedure VOIP($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Container_Ext($alias, "Sipgate",  "VOIP SaaS", "Provides a Voice over IP Phone Service to contact Teachers and Customers.")
!endprocedure
