/' include of C4 libaries '/
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

/' Persons '/
/' Predefined Persons to be used in other PlantUMLs '/
/' teacher(,) '/
/' student(,) '/
/' support(,) '/

!unquoted procedure $teacher($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person_Ext($alias, "Teacher", "A teacher using the adaptive learning system.")
!endprocedure
!unquoted procedure $student($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person_Ext($alias, "Student", "A student using the adaptive learning system.")
!endprocedure
!unquoted procedure $support($alias, $label, $descr="", $sprite="", $tags="", $link="", $type="")
Person($alias, "Service & Support", "A internal role supporting our users and customers.")
!endprocedure


